### ISSUE TITLE
Is this available for Mac?

### ISSUE THREAD

**Issue by Emolus** [Gavin770/champGG#10]
Hi, 

I've been downloading the patches from a reddit thread, but since 5.22 came out I can't seem to get it. Is this available for Mac? Thanks

**Comment by Delogrand770** [comment]
Not at the moment because I don't have a Mac to test on. Since it is coded
using nwjs.io (chromium) and web other web technologies the conversion may
be as simple as changing out the binaries for the OSX version of nwjs.
However, I suspect there are some minor differences or assumptions I made
when coding for windows that will prevent that from working.

Someone on the /r/leagueoflegends sub made a similar program to mine that works with Mac.
https://github.com/dustinblackman/Championify/releases/latest

I can't vouch for the program as I have never used it but it seems to be successful.
