### ISSUE TITLE
Space at end of folder name

### ISSUE THREAD

**Issue by mphartzheim** [Gavin770/champGG#8]
The current data set is being downloaded and put into a folder with a space at the end of the folder name.

"\ItemSets\22 JUN 2015 - PATCH \"

The space on the end does not play nicely with Windows. Namely, you cannot rename or delete the folder as Windows says that it cannot find the folder.

**Comment by Delogrand770** [comment]
Nice catch, I'll get a fix out ASAP

**Comment by Delogrand770** [comment]
So the problem was champion.gg changed their HTML for how they showed the current patch. This caused the HTML scrape to fail and I never thought of that happening. I updated the app to find the new patch version and I fixed it from ever putting trailing spaces again if (when) they change their site HTML.

**Comment by Delogrand770** [comment]
Steps to remove a bugged ItemSets directory
1. Right click near but not on the ItemSets folder while holding shift
2. Select "Open Command Window Here"
3. Type the command below and press enter

rd /s /q ItemSets
